"""create base tables

Revision ID: 8ab241e6321c
Revises: 
Create Date: 2026-06-18 13:58:27.839522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab241e6321c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_knowledge_base_id'), 'agent_runs', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_id'), 'agent_runs', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_type'), 'agent_runs', ['task_type'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('is_retry', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_created_at'), 'agent_steps', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_steps_is_retry'), 'agent_steps', ['is_retry'], unique=False)
    op.create_index(op.f('ix_agent_steps_retry_count'), 'agent_steps', ['retry_count'], unique=False)
    op.create_index(op.f('ix_agent_steps_status'), 'agent_steps', ['status'], unique=False)
    op.create_index(op.f('ix_agent_steps_step_name'), 'agent_steps', ['step_name'], unique=False)
    op.create_index(op.f('ix_agent_steps_step_type'), 'agent_steps', ['step_type'], unique=False)
    op.create_index(op.f('ix_agent_steps_task_id'), 'agent_steps', ['task_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('markdown_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Text(), nullable=True),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_created_at'), 'agent_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_tasks_job_id'), 'agent_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_knowledge_base_id'), 'agent_tasks', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_progress'), 'agent_tasks', ['progress'], unique=False)
    op.create_index(op.f('ix_agent_tasks_report_id'), 'agent_tasks', ['report_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_retry_count'), 'agent_tasks', ['retry_count'], unique=False)
    op.create_index(op.f('ix_agent_tasks_session_id'), 'agent_tasks', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_task_type'), 'agent_tasks', ['task_type'], unique=False)
    op.create_table('bad_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feedback_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trace_snapshot', sa.JSON(), nullable=True),
    sa.Column('fixed_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('fixed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bad_cases_category'), 'bad_cases', ['category'], unique=False)
    op.create_index(op.f('ix_bad_cases_created_at'), 'bad_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_bad_cases_feedback_source'), 'bad_cases', ['feedback_source'], unique=False)
    op.create_index(op.f('ix_bad_cases_fixed_at'), 'bad_cases', ['fixed_at'], unique=False)
    op.create_index(op.f('ix_bad_cases_prompt_name'), 'bad_cases', ['prompt_name'], unique=False)
    op.create_index(op.f('ix_bad_cases_prompt_version'), 'bad_cases', ['prompt_version'], unique=False)
    op.create_index(op.f('ix_bad_cases_severity'), 'bad_cases', ['severity'], unique=False)
    op.create_index(op.f('ix_bad_cases_status'), 'bad_cases', ['status'], unique=False)
    op.create_index(op.f('ix_bad_cases_task_id'), 'bad_cases', ['task_id'], unique=False)
    op.create_index(op.f('ix_bad_cases_task_type'), 'bad_cases', ['task_type'], unique=False)
    op.create_index(op.f('ix_bad_cases_user_id'), 'bad_cases', ['user_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_created_at'), 'llm_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_calls_input_tokens'), 'llm_calls', ['input_tokens'], unique=False)
    op.create_index(op.f('ix_llm_calls_latency_ms'), 'llm_calls', ['latency_ms'], unique=False)
    op.create_index(op.f('ix_llm_calls_model_name'), 'llm_calls', ['model_name'], unique=False)
    op.create_index(op.f('ix_llm_calls_output_tokens'), 'llm_calls', ['output_tokens'], unique=False)
    op.create_index(op.f('ix_llm_calls_prompt_name'), 'llm_calls', ['prompt_name'], unique=False)
    op.create_index(op.f('ix_llm_calls_prompt_version'), 'llm_calls', ['prompt_version'], unique=False)
    op.create_index(op.f('ix_llm_calls_status'), 'llm_calls', ['status'], unique=False)
    op.create_index(op.f('ix_llm_calls_step_id'), 'llm_calls', ['step_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_task_id'), 'llm_calls', ['task_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_total_tokens'), 'llm_calls', ['total_tokens'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_content', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_created_at'), 'prompt_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_versions_is_active'), 'prompt_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompt_versions_prompt_name'), 'prompt_versions', ['prompt_name'], unique=False)
    op.create_index(op.f('ix_prompt_versions_prompt_version'), 'prompt_versions', ['prompt_version'], unique=False)
    op.create_index(op.f('ix_prompt_versions_task_type'), 'prompt_versions', ['task_type'], unique=False)
    op.create_table('rag_retrieval_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('retrieved_count', sa.Integer(), nullable=False),
    sa.Column('matched_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_retrieval_logs_created_at'), 'rag_retrieval_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_retrieval_logs_knowledge_base_id'), 'rag_retrieval_logs', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_rag_retrieval_logs_latency_ms'), 'rag_retrieval_logs', ['latency_ms'], unique=False)
    op.create_index(op.f('ix_rag_retrieval_logs_retrieved_count'), 'rag_retrieval_logs', ['retrieved_count'], unique=False)
    op.create_index(op.f('ix_rag_retrieval_logs_status'), 'rag_retrieval_logs', ['status'], unique=False)
    op.create_index(op.f('ix_rag_retrieval_logs_step_id'), 'rag_retrieval_logs', ['step_id'], unique=False)
    op.create_index(op.f('ix_rag_retrieval_logs_task_id'), 'rag_retrieval_logs', ['task_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('markdown_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_agent_run_id'), 'reports', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_source_type'), 'reports', ['source_type'], unique=False)
    op.create_index(op.f('ix_reports_title'), 'reports', ['title'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('tool_output', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_created_at'), 'tool_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_tool_calls_latency_ms'), 'tool_calls', ['latency_ms'], unique=False)
    op.create_index(op.f('ix_tool_calls_status'), 'tool_calls', ['status'], unique=False)
    op.create_index(op.f('ix_tool_calls_step_id'), 'tool_calls', ['step_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_task_id'), 'tool_calls', ['task_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_tool_name'), 'tool_calls', ['tool_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('project_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_spaces_name'), 'project_spaces', ['name'], unique=False)
    op.create_index(op.f('ix_project_spaces_owner_id'), 'project_spaces', ['owner_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_spaces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_project_id'), 'chat_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_title'), 'chat_sessions', ['title'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_spaces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_name'), 'knowledge_bases', ['name'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_project_id'), 'knowledge_bases', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_spaces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member_project_user')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_role'), 'project_members', ['role'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_knowledge_base_id'), 'documents', ['knowledge_base_id'], unique=False)
    op.create_table('rag_eval_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_document_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('should_refuse', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_chunk_index'), 'document_chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('rag_eval_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eval_run_id', sa.Integer(), nullable=False),
    sa.Column('eval_case_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actual_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('should_refuse', sa.Boolean(), nullable=False),
    sa.Column('actual_refused', sa.Boolean(), nullable=False),
    sa.Column('confidence_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matched_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('missing_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hit_expected_keywords', sa.Boolean(), nullable=False),
    sa.Column('expected_document_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hit_expected_document', sa.Boolean(), nullable=False),
    sa.Column('citation_valid', sa.Boolean(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('citations_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eval_case_id'], ['rag_eval_cases.id'], ),
    sa.ForeignKeyConstraint(['eval_run_id'], ['rag_eval_runs.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_eval_results')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_index'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('rag_eval_runs')
    op.drop_table('rag_eval_cases')
    op.drop_index(op.f('ix_documents_knowledge_base_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_role'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_knowledge_bases_project_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_name'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_title'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_project_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_project_spaces_owner_id'), table_name='project_spaces')
    op.drop_index(op.f('ix_project_spaces_name'), table_name='project_spaces')
    op.drop_table('project_spaces')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tool_calls_tool_name'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_task_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_step_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_status'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_latency_ms'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_created_at'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_reports_title'), table_name='reports')
    op.drop_index(op.f('ix_reports_source_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_agent_run_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_rag_retrieval_logs_task_id'), table_name='rag_retrieval_logs')
    op.drop_index(op.f('ix_rag_retrieval_logs_step_id'), table_name='rag_retrieval_logs')
    op.drop_index(op.f('ix_rag_retrieval_logs_status'), table_name='rag_retrieval_logs')
    op.drop_index(op.f('ix_rag_retrieval_logs_retrieved_count'), table_name='rag_retrieval_logs')
    op.drop_index(op.f('ix_rag_retrieval_logs_latency_ms'), table_name='rag_retrieval_logs')
    op.drop_index(op.f('ix_rag_retrieval_logs_knowledge_base_id'), table_name='rag_retrieval_logs')
    op.drop_index(op.f('ix_rag_retrieval_logs_created_at'), table_name='rag_retrieval_logs')
    op.drop_table('rag_retrieval_logs')
    op.drop_index(op.f('ix_prompt_versions_task_type'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_prompt_version'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_prompt_name'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_is_active'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_created_at'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_llm_calls_total_tokens'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_task_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_step_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_status'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_prompt_version'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_prompt_name'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_output_tokens'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_model_name'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_latency_ms'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_input_tokens'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_created_at'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_bad_cases_user_id'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_task_type'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_task_id'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_status'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_severity'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_prompt_version'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_prompt_name'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_fixed_at'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_feedback_source'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_created_at'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_category'), table_name='bad_cases')
    op.drop_table('bad_cases')
    op.drop_index(op.f('ix_agent_tasks_task_type'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_session_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_retry_count'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_report_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_progress'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_knowledge_base_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_job_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_created_at'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_agent_steps_task_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_step_type'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_step_name'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_status'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_retry_count'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_is_retry'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_created_at'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_agent_runs_task_type'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_task_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_knowledge_base_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
